// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHVqOEwbR8jIH4UtrhQCDTH6X6kPwjjJI',
    appId: '1:1092555321256:web:b57b5084e125b3ae23f79d',
    messagingSenderId: '1092555321256',
    projectId: 'ayurvedicfood-593c1',
    authDomain: 'ayurvedicfood-593c1.firebaseapp.com',
    storageBucket: 'ayurvedicfood-593c1.appspot.com',
    measurementId: 'G-MH3LFZMDXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJevIkzCtsR0a0kCpOsLgLfkdBE8-A-M',
    appId: '1:1092555321256:android:cc8b6af243571aa223f79d',
    messagingSenderId: '1092555321256',
    projectId: 'ayurvedicfood-593c1',
    storageBucket: 'ayurvedicfood-593c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoF9hp99n7ui38KZTnaZnVvwrAV-jOcLs',
    appId: '1:1092555321256:ios:6f1b135d22dc244223f79d',
    messagingSenderId: '1092555321256',
    projectId: 'ayurvedicfood-593c1',
    storageBucket: 'ayurvedicfood-593c1.appspot.com',
    iosClientId:
        '1092555321256-h4gv7hhp991emufikpf1nm9jf4o9hufn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayurvedic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoF9hp99n7ui38KZTnaZnVvwrAV-jOcLs',
    appId: '1:1092555321256:ios:6f1b135d22dc244223f79d',
    messagingSenderId: '1092555321256',
    projectId: 'ayurvedicfood-593c1',
    storageBucket: 'ayurvedicfood-593c1.appspot.com',
    iosClientId:
        '1092555321256-h4gv7hhp991emufikpf1nm9jf4o9hufn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayurvedic',
  );
}
